import = ["/Users/biubiu/.config/alacritty/alabaster.toml", "/Users/biubiu/.config/alacritty/fonts.toml"]
# import = ["/Users/biubiu/.config/alacritty/fonts.toml"]
# Maple Mono SC NF
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[window]
blur = false
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
option_as_alt = "Both"
resize_increments = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 35



